# ??!!! ?? ??? ?? ? ?? ?????.
# ?! git.ignore ??? ? ??? ?? ????.

  # ??? smtp(Simple Mail Transfer Protocol) server ??
  # ?? ??? ??? ?? 30?, ?? ?? 100??? ?????. 30? ???? ????? ???.
spring:
  mail:
    host: smtp.naver.com #smtp ?? ??
    port: 465 # ??? smtp ?? ?? (??? ??. ?? ?? ??)
    username: dpevent@naver.com # ?? ? ?? ??!!!
    password: emailTest1  # ?? ? ?? ??!!
    properties:
      mail:
        smtp:
          starttls:     # Transport Layer Security
            enable: true
          auth: true    # SMTP AUTH - ??? ???? ??, ??? ID? ????? ???? ?
          ssl:          # Secure Sokets Layer . ?????? smtp ??? ? , ?? ??? '?? ??(SSL) ??' ?? ??? ??
            enable: true